// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.chat.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The CreateThreadResponse model. */
@Fluent
public final class CreateThreadResponse {
    /*
     * Thread Id
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * Get the id property: Thread Id.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Set the id property: Thread Id.
     *
     * @param id the id value to set.
     * @return the CreateThreadResponse object itself.
     */
    public CreateThreadResponse setId(String id) {
        this.id = id;
        return this;
    }
}
