// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.chat.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The CreateMessageRequest model. */
@Fluent
public final class CreateMessageRequest {
    /*
     * This Id is a client-specific Id in a numeric unsigned Int64 format. It
     * can be used for client deduping, among other client usages.
     */
    @JsonProperty(value = "clientMessageId")
    private String clientMessageId;

    /*
     * The priority property.
     */
    @JsonProperty(value = "priority")
    private MessagePriority priority;

    /*
     * Chat message content.
     */
    @JsonProperty(value = "content", required = true)
    private String content;

    /*
     * The display name of the sender.
     */
    @JsonProperty(value = "senderDisplayName")
    private String senderDisplayName;

    /**
     * Get the clientMessageId property: This Id is a client-specific Id in a numeric unsigned Int64 format. It can be
     * used for client deduping, among other client usages.
     *
     * @return the clientMessageId value.
     */
    public String getClientMessageId() {
        return this.clientMessageId;
    }

    /**
     * Set the clientMessageId property: This Id is a client-specific Id in a numeric unsigned Int64 format. It can be
     * used for client deduping, among other client usages.
     *
     * @param clientMessageId the clientMessageId value to set.
     * @return the CreateMessageRequest object itself.
     */
    public CreateMessageRequest setClientMessageId(String clientMessageId) {
        this.clientMessageId = clientMessageId;
        return this;
    }

    /**
     * Get the priority property: The priority property.
     *
     * @return the priority value.
     */
    public MessagePriority getPriority() {
        return this.priority;
    }

    /**
     * Set the priority property: The priority property.
     *
     * @param priority the priority value to set.
     * @return the CreateMessageRequest object itself.
     */
    public CreateMessageRequest setPriority(MessagePriority priority) {
        this.priority = priority;
        return this;
    }

    /**
     * Get the content property: Chat message content.
     *
     * @return the content value.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Set the content property: Chat message content.
     *
     * @param content the content value to set.
     * @return the CreateMessageRequest object itself.
     */
    public CreateMessageRequest setContent(String content) {
        this.content = content;
        return this;
    }

    /**
     * Get the senderDisplayName property: The display name of the sender.
     *
     * @return the senderDisplayName value.
     */
    public String getSenderDisplayName() {
        return this.senderDisplayName;
    }

    /**
     * Set the senderDisplayName property: The display name of the sender.
     *
     * @param senderDisplayName the senderDisplayName value to set.
     * @return the CreateMessageRequest object itself.
     */
    public CreateMessageRequest setSenderDisplayName(String senderDisplayName) {
        this.senderDisplayName = senderDisplayName;
        return this;
    }
}
