// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.chat.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The CreateMessageResponse model. */
@Fluent
public final class CreateMessageResponse {
    /*
     * The id of the message. This id is server generated.
     */
    @JsonProperty(value = "id")
    private String id;

    /*
     * This Id is a client-specific Id in a numeric unsigned Int64 format. It
     * can be used for client deduping, among other client usages.
     */
    @JsonProperty(value = "clientMessageId")
    private String clientMessageId;

    /**
     * Get the id property: The id of the message. This id is server generated.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Set the id property: The id of the message. This id is server generated.
     *
     * @param id the id value to set.
     * @return the CreateMessageResponse object itself.
     */
    public CreateMessageResponse setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the clientMessageId property: This Id is a client-specific Id in a numeric unsigned Int64 format. It can be
     * used for client deduping, among other client usages.
     *
     * @return the clientMessageId value.
     */
    public String getClientMessageId() {
        return this.clientMessageId;
    }

    /**
     * Set the clientMessageId property: This Id is a client-specific Id in a numeric unsigned Int64 format. It can be
     * used for client deduping, among other client usages.
     *
     * @param clientMessageId the clientMessageId value to set.
     * @return the CreateMessageResponse object itself.
     */
    public CreateMessageResponse setClientMessageId(String clientMessageId) {
        this.clientMessageId = clientMessageId;
        return this;
    }
}
