// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.chat.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The GetThreadsResponse model. */
@Fluent
public final class GetThreadsResponse {
    /*
     * List of threads.
     */
    @JsonProperty(value = "threads")
    private List<Thread> threads;

    /*
     * Continuation link to get new and edited threads
     */
    @JsonProperty(value = "syncState")
    private String syncState;

    /*
     * If there are more threads that can be retrieved, the backward link will
     * be populated.
     */
    @JsonProperty(value = "backwardLink")
    private String backwardLink;

    /**
     * Get the threads property: List of threads.
     *
     * @return the threads value.
     */
    public List<Thread> getThreads() {
        return this.threads;
    }

    /**
     * Set the threads property: List of threads.
     *
     * @param threads the threads value to set.
     * @return the GetThreadsResponse object itself.
     */
    public GetThreadsResponse setThreads(List<Thread> threads) {
        this.threads = threads;
        return this;
    }

    /**
     * Get the syncState property: Continuation link to get new and edited threads.
     *
     * @return the syncState value.
     */
    public String getSyncState() {
        return this.syncState;
    }

    /**
     * Set the syncState property: Continuation link to get new and edited threads.
     *
     * @param syncState the syncState value to set.
     * @return the GetThreadsResponse object itself.
     */
    public GetThreadsResponse setSyncState(String syncState) {
        this.syncState = syncState;
        return this;
    }

    /**
     * Get the backwardLink property: If there are more threads that can be retrieved, the backward link will be
     * populated.
     *
     * @return the backwardLink value.
     */
    public String getBackwardLink() {
        return this.backwardLink;
    }

    /**
     * Set the backwardLink property: If there are more threads that can be retrieved, the backward link will be
     * populated.
     *
     * @param backwardLink the backwardLink value to set.
     * @return the GetThreadsResponse object itself.
     */
    public GetThreadsResponse setBackwardLink(String backwardLink) {
        this.backwardLink = backwardLink;
        return this;
    }
}
