// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.chat.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for MemberRole. */
public final class MemberRole extends ExpandableStringEnum<MemberRole> {
    /** Static value Admin for MemberRole. */
    public static final MemberRole ADMIN = fromString("Admin");

    /** Static value User for MemberRole. */
    public static final MemberRole USER = fromString("User");

    /**
     * Creates or finds a MemberRole from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding MemberRole.
     */
    @JsonCreator
    public static MemberRole fromString(String name) {
        return fromString(name, MemberRole.class);
    }

    /** @return known MemberRole values. */
    public static Collection<MemberRole> values() {
        return values(MemberRole.class);
    }
}
