// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.chat.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for MessagePriority. */
public final class MessagePriority extends ExpandableStringEnum<MessagePriority> {
    /** Static value Normal for MessagePriority. */
    public static final MessagePriority NORMAL = fromString("Normal");

    /** Static value High for MessagePriority. */
    public static final MessagePriority HIGH = fromString("High");

    /**
     * Creates or finds a MessagePriority from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding MessagePriority.
     */
    @JsonCreator
    public static MessagePriority fromString(String name) {
        return fromString(name, MessagePriority.class);
    }

    /** @return known MessagePriority values. */
    public static Collection<MessagePriority> values() {
        return values(MessagePriority.class);
    }
}
