// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.chat.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The ReadReceipt model. */
@Fluent
public final class ReadReceipt {
    /*
     * Id for `ReadReceipt` sender
     */
    @JsonProperty(value = "userId")
    private String userId;

    /*
     * Id for the message that has been read. This id is server generated.
     */
    @JsonProperty(value = "messageId")
    private String messageId;

    /*
     * Read receipt timestamp
     */
    @JsonProperty(value = "readTimestamp")
    private Long readTimestamp;

    /*
     * Client message id specified in the
     * Microsoft.AzureCommunicationService.Gateway.Models.Client.CreateMessageRequest.
     * This Id is a client-specific Id in a numeric unsigned Int64 format. It
     * can be used for client deduping, among other client usages.
     */
    @JsonProperty(value = "clientMessageId")
    private String clientMessageId;

    /**
     * Get the userId property: Id for `ReadReceipt` sender.
     *
     * @return the userId value.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Set the userId property: Id for `ReadReceipt` sender.
     *
     * @param userId the userId value to set.
     * @return the ReadReceipt object itself.
     */
    public ReadReceipt setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Get the messageId property: Id for the message that has been read. This id is server generated.
     *
     * @return the messageId value.
     */
    public String getMessageId() {
        return this.messageId;
    }

    /**
     * Set the messageId property: Id for the message that has been read. This id is server generated.
     *
     * @param messageId the messageId value to set.
     * @return the ReadReceipt object itself.
     */
    public ReadReceipt setMessageId(String messageId) {
        this.messageId = messageId;
        return this;
    }

    /**
     * Get the readTimestamp property: Read receipt timestamp.
     *
     * @return the readTimestamp value.
     */
    public Long getReadTimestamp() {
        return this.readTimestamp;
    }

    /**
     * Set the readTimestamp property: Read receipt timestamp.
     *
     * @param readTimestamp the readTimestamp value to set.
     * @return the ReadReceipt object itself.
     */
    public ReadReceipt setReadTimestamp(Long readTimestamp) {
        this.readTimestamp = readTimestamp;
        return this;
    }

    /**
     * Get the clientMessageId property: Client message id specified in the
     * Microsoft.AzureCommunicationService.Gateway.Models.Client.CreateMessageRequest. This Id is a client-specific Id
     * in a numeric unsigned Int64 format. It can be used for client deduping, among other client usages.
     *
     * @return the clientMessageId value.
     */
    public String getClientMessageId() {
        return this.clientMessageId;
    }

    /**
     * Set the clientMessageId property: Client message id specified in the
     * Microsoft.AzureCommunicationService.Gateway.Models.Client.CreateMessageRequest. This Id is a client-specific Id
     * in a numeric unsigned Int64 format. It can be used for client deduping, among other client usages.
     *
     * @param clientMessageId the clientMessageId value to set.
     * @return the ReadReceipt object itself.
     */
    public ReadReceipt setClientMessageId(String clientMessageId) {
        this.clientMessageId = clientMessageId;
        return this;
    }
}
