// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.chat.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The ThreadMember model. */
@Fluent
public final class ThreadMember {
    /*
     * The id of the thread member in the format `8:spool:ResourceId_AcsUserId`
     */
    @JsonProperty(value = "id", required = true)
    private String id;

    /*
     * Display name for the thread member
     */
    @JsonProperty(value = "displayName")
    private String displayName;

    /*
     * Role of the thread member. The valid value should be "User" or "Admin".
     */
    @JsonProperty(value = "memberRole", required = true)
    private MemberRole memberRole;

    /*
     * Time from which the group chat history is shared with the member in
     * EPOCH time (milliseconds)
     */
    @JsonProperty(value = "shareHistoryTime")
    private String shareHistoryTime;

    /**
     * Get the id property: The id of the thread member in the format `8:spool:ResourceId_AcsUserId`.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Set the id property: The id of the thread member in the format `8:spool:ResourceId_AcsUserId`.
     *
     * @param id the id value to set.
     * @return the ThreadMember object itself.
     */
    public ThreadMember setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the displayName property: Display name for the thread member.
     *
     * @return the displayName value.
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Set the displayName property: Display name for the thread member.
     *
     * @param displayName the displayName value to set.
     * @return the ThreadMember object itself.
     */
    public ThreadMember setDisplayName(String displayName) {
        this.displayName = displayName;
        return this;
    }

    /**
     * Get the memberRole property: Role of the thread member. The valid value should be "User" or "Admin".
     *
     * @return the memberRole value.
     */
    public MemberRole getMemberRole() {
        return this.memberRole;
    }

    /**
     * Set the memberRole property: Role of the thread member. The valid value should be "User" or "Admin".
     *
     * @param memberRole the memberRole value to set.
     * @return the ThreadMember object itself.
     */
    public ThreadMember setMemberRole(MemberRole memberRole) {
        this.memberRole = memberRole;
        return this;
    }

    /**
     * Get the shareHistoryTime property: Time from which the group chat history is shared with the member in EPOCH time
     * (milliseconds).
     *
     * @return the shareHistoryTime value.
     */
    public String getShareHistoryTime() {
        return this.shareHistoryTime;
    }

    /**
     * Set the shareHistoryTime property: Time from which the group chat history is shared with the member in EPOCH time
     * (milliseconds).
     *
     * @param shareHistoryTime the shareHistoryTime value to set.
     * @return the ThreadMember object itself.
     */
    public ThreadMember setShareHistoryTime(String shareHistoryTime) {
        this.shareHistoryTime = shareHistoryTime;
        return this;
    }
}
