// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.chat.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The UpdateThreadRequest model. */
@Fluent
public final class UpdateThreadRequest {
    /*
     * Thread topic
     */
    @JsonProperty(value = "topic", required = true)
    private String topic;

    /**
     * Get the topic property: Thread topic.
     *
     * @return the topic value.
     */
    public String getTopic() {
        return this.topic;
    }

    /**
     * Set the topic property: Thread topic.
     *
     * @param topic the topic value to set.
     * @return the UpdateThreadRequest object itself.
     */
    public UpdateThreadRequest setTopic(String topic) {
        this.topic = topic;
        return this;
    }
}
