// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.chat.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The UpdateMessageRequest model. */
@Fluent
public final class UpdateMessageRequest {
    /*
     * Chat message content.
     */
    @JsonProperty(value = "content", required = true)
    private String content;

    /**
     * Get the content property: Chat message content.
     *
     * @return the content value.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Set the content property: Chat message content.
     *
     * @param content the content value to set.
     * @return the UpdateMessageRequest object itself.
     */
    public UpdateMessageRequest setContent(String content) {
        this.content = content;
        return this;
    }
}
